### ISSUE TITLE
Big performance issue when page contains lot of data.

### ISSUE THREAD

**Issue by fkranenburg** [VoIPGRID/chrome-extension#25]
There is a big performance problem with this plugin if there are a lot of elements on the current page. We are developing a CRM system where we experience long delays and blocking user experience if this Chrome plugin is active. We use for example 'http://dgrid.io' grid for displaying our data. On their test site you can easily reproduce the issue. If you navigate to this site, your browser will become unresponsive for seconds.

http://dgrid.io/js/dgrid/test/performance.html

When you disable this plugin in de extension manager the problem is gone. 

Maybe there is any way to loop through the DOM elements in a non-blocking way, for example using setTimeout?

**Comment by fkranenburg** [comment]
I've forked it and rather quickly and ugly implemented the [TreeWalker API](https://developer.mozilla.org/nl/docs/Web/API/TreeWalker) in the current version. As a result the plugin is much faster and it seems to completely solve the performance problems within our CRM application and the above testpage.

Please check out my [commit here](https://github.com/fkranenburg/chrome-extension/commit/1fde9ec38dc3a6690ae40a9b7355a58b9882e4aa
).

This commit is more like to show the performance could be improved using the TreeWalker, but I'm not really sure it broke something else ;-)

**Comment by cpoppema** [comment]
Hi @fkranenburg, thanks for taking the time to report _and_ improve this plugin! The TreeWalker API  looks very interesting and I will certainly implement it and hope to see the same results you saw!

**Comment by cpoppema** [comment]
To give you an update @fkranenburg: I've just put this on github: https://github.com/VoIPGRID/chrome-extension/tree/feature/improve-performance-mutations. This shows a lot of promise in improving performance, most noticably on websites using javascript to modify the DOM. It's not as fast as your own commit, but after some testing your code unfortunately has some unintentional (but unwanted) side-effects. For instance, when using a TreeWalker and removing a node from the DOM (which happens since we're replacing those), the walker would no longer return new nodes and therefore only  a single phone number would've been recognized and get an icon injected. In my branch you can see I'm using a NodeIterator (TreeWalker uses this as well in the background) and using this instead it works properly: it will still return nodes after removing nodes from the DOM.

On a page with a lot of data that is already present at the time of the DOMContentLoaded event, switching from the current recursive iteration of the DOM to a NodeIterator does not help as much; the DOM is only walked once in both cases. I do see huge performance gain when re-iterating through the DOM (this happens when scanning mutations) in favor of NodeIterator.

To make it even faster altogether I've also added some rules to check before attempting to fully parse a text as you can see in the changes in dutch.js. Together it can bring down the number of elements traversed and strings being parsed.

I want to get this up and running in the Firefox plugin as well and hope to be able to re-use as much code as possible, while doing that I will perform some more tests to see if the detection still covers everything it does currently.

**Comment by fkranenburg** [comment]
I have added some updates in my last commit to prevent those unwanted sideeffects of my initial commit, this is the version we currently using my fork internally (3 people) without any problems, multiple numbers are now checked correctly and previous processed nodes are not processed again. Se my last commit (again, I may have removed some other functionality). https://github.com/fkranenburg/chrome-extension/commit/7d028eb21f8fae9520e48fc7a529ce06f86a065e

**Comment by fkranenburg** [comment]
The NodeIterator looks interesting. We are looking forward to this version of the plugin. Thanks.

**Comment by cpoppema** [comment]
@fkranenburg: in the next few hours version 1.4.8 of the chrome extension should become available in the chrome webstore.
